name: Build kernel

env:
  ###################################
  # ★ 小米8 dipper — MIUI 底包示例 #
  ###################################
  kernel_repository: MiCode/Xiaomi_Kernel_OpenSource
  kernel_branch: dipper-q-oss
  device: dipper
  defconfig: |
    dipper_defconfig
  kernel_patch: |
    backport-path-umount.patch
    50_add_susfs_in_kernel-4.9.patch
  kernelsu_patch: |

on:
  workflow_dispatch:
    inputs:
      allow_rebuild:
        description: "Allow Rebuild"
        type: boolean
        default: false

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt u
